---
# This playbook contains zabbix agent -> zfs on linux plays
#
# Based on https://share.zabbix.com/operating-systems/linux/zfs-on-linux

- name: Set is_jail
  ansible.builtin.set_fact:
    is_jail: "{{ 'jails' in ansible_virtualization_tech_guest }}"

- name: Remove deprecated local-userparameter-zfs.conf
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf_dir }}/local-userparameter-zfs.conf"
    state: absent
  notify: Restart zabbix-agent

- name: Copy binaries
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/bin/
    mode: "755"
  loop:
    - zabbix-lld-zfs-filesets
    - zabbix-lld-zfs-pools
  notify: Restart zabbix-agent
  when: "ansible_system != 'FreeBSD' or not is_jail"

- name: Add zabbix-agent configuration file
  ansible.builtin.copy:
    src: "{{ ansible_system }}/local-userparameter_zfs.conf"
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: "644"
  notify: Restart zabbix-agent
  when: "ansible_system != 'FreeBSD' or not is_jail"

- name: Remove deprecated sudo rules for zfs access
  ansible.builtin.file:
    dest: "{{ etc_prefix }}/etc/sudoers.d/local-mit-zabbix-agent-zfs"
    state: absent
  # FreeBSD never used sudo for zfs
  when: ansible_distribution == 'Debian'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Logcheck rules
  # The file has to be named "local", either "a", "0-mit-zabbix-agent-check-upgrades"
  # or "mit-zabbix-agent-check-upgrades" do not work. Test with:
  # sudo -u logcheck logcheck -o -t -d -l /var/log/auth.log
  ansible.builtin.lineinfile:
    create: true
    path: /etc/logcheck/violations.ignore.d/local
    line: "^\\w{3} [ :0-9]{11} [._[:alnum:]-]+ sudo:   zabbix : PWD=\\/ ; USER=root ; COMMAND=\\/sbin\\/(zfs|zpool) .*"
    mode: "644"
  when: "'logcheck' in ansible_facts.packages and ansible_distribution == 'Debian' and ansible_distribution_major_version|int == 11"
